###
POST http://localhost:8092/api/v1/individual/reg
Content-Type: application/json

{
  "passportNumber": "AB123456",
  "phoneNumber": "+79001234567",
  "status": "OK"
}

###
GET  http://localhost:8098/api/users/ID
Content-Type: application/json